/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SucessoRouteImport } from './routes/sucesso'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ClienteRouteImport } from './routes/cliente'
import { Route as AgendarRouteImport } from './routes/agendar'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminServicosRouteImport } from './routes/admin/servicos'
import { Route as AdminHorariosRouteImport } from './routes/admin/horarios'
import { Route as AdminBarbeirosRouteImport } from './routes/admin/barbeiros'

const SucessoRoute = SucessoRouteImport.update({
  id: '/sucesso',
  path: '/sucesso',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ClienteRoute = ClienteRouteImport.update({
  id: '/cliente',
  path: '/cliente',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendarRoute = AgendarRouteImport.update({
  id: '/agendar',
  path: '/agendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminServicosRoute = AdminServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHorariosRoute = AdminHorariosRouteImport.update({
  id: '/horarios',
  path: '/horarios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBarbeirosRoute = AdminBarbeirosRouteImport.update({
  id: '/barbeiros',
  path: '/barbeiros',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/agendar': typeof AgendarRoute
  '/cliente': typeof ClienteRoute
  '/login': typeof LoginRoute
  '/sucesso': typeof SucessoRoute
  '/admin/barbeiros': typeof AdminBarbeirosRoute
  '/admin/horarios': typeof AdminHorariosRoute
  '/admin/servicos': typeof AdminServicosRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agendar': typeof AgendarRoute
  '/cliente': typeof ClienteRoute
  '/login': typeof LoginRoute
  '/sucesso': typeof SucessoRoute
  '/admin/barbeiros': typeof AdminBarbeirosRoute
  '/admin/horarios': typeof AdminHorariosRoute
  '/admin/servicos': typeof AdminServicosRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/agendar': typeof AgendarRoute
  '/cliente': typeof ClienteRoute
  '/login': typeof LoginRoute
  '/sucesso': typeof SucessoRoute
  '/admin/barbeiros': typeof AdminBarbeirosRoute
  '/admin/horarios': typeof AdminHorariosRoute
  '/admin/servicos': typeof AdminServicosRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/agendar'
    | '/cliente'
    | '/login'
    | '/sucesso'
    | '/admin/barbeiros'
    | '/admin/horarios'
    | '/admin/servicos'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agendar'
    | '/cliente'
    | '/login'
    | '/sucesso'
    | '/admin/barbeiros'
    | '/admin/horarios'
    | '/admin/servicos'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/agendar'
    | '/cliente'
    | '/login'
    | '/sucesso'
    | '/admin/barbeiros'
    | '/admin/horarios'
    | '/admin/servicos'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AgendarRoute: typeof AgendarRoute
  ClienteRoute: typeof ClienteRoute
  LoginRoute: typeof LoginRoute
  SucessoRoute: typeof SucessoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sucesso': {
      id: '/sucesso'
      path: '/sucesso'
      fullPath: '/sucesso'
      preLoaderRoute: typeof SucessoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cliente': {
      id: '/cliente'
      path: '/cliente'
      fullPath: '/cliente'
      preLoaderRoute: typeof ClienteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agendar': {
      id: '/agendar'
      path: '/agendar'
      fullPath: '/agendar'
      preLoaderRoute: typeof AgendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/servicos': {
      id: '/admin/servicos'
      path: '/servicos'
      fullPath: '/admin/servicos'
      preLoaderRoute: typeof AdminServicosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/horarios': {
      id: '/admin/horarios'
      path: '/horarios'
      fullPath: '/admin/horarios'
      preLoaderRoute: typeof AdminHorariosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/barbeiros': {
      id: '/admin/barbeiros'
      path: '/barbeiros'
      fullPath: '/admin/barbeiros'
      preLoaderRoute: typeof AdminBarbeirosRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminBarbeirosRoute: typeof AdminBarbeirosRoute
  AdminHorariosRoute: typeof AdminHorariosRoute
  AdminServicosRoute: typeof AdminServicosRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBarbeirosRoute: AdminBarbeirosRoute,
  AdminHorariosRoute: AdminHorariosRoute,
  AdminServicosRoute: AdminServicosRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AgendarRoute: AgendarRoute,
  ClienteRoute: ClienteRoute,
  LoginRoute: LoginRoute,
  SucessoRoute: SucessoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
