/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SucessoRouteImport } from './routes/sucesso'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AgendarRouteImport } from './routes/agendar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'

const SucessoRoute = SucessoRouteImport.update({
  id: '/sucesso',
  path: '/sucesso',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendarRoute = AgendarRouteImport.update({
  id: '/agendar',
  path: '/agendar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agendar': typeof AgendarRoute
  '/login': typeof LoginRoute
  '/sucesso': typeof SucessoRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agendar': typeof AgendarRoute
  '/login': typeof LoginRoute
  '/sucesso': typeof SucessoRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agendar': typeof AgendarRoute
  '/login': typeof LoginRoute
  '/sucesso': typeof SucessoRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/agendar' | '/login' | '/sucesso' | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/agendar' | '/login' | '/sucesso' | '/admin'
  id: '__root__' | '/' | '/agendar' | '/login' | '/sucesso' | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendarRoute: typeof AgendarRoute
  LoginRoute: typeof LoginRoute
  SucessoRoute: typeof SucessoRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sucesso': {
      id: '/sucesso'
      path: '/sucesso'
      fullPath: '/sucesso'
      preLoaderRoute: typeof SucessoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agendar': {
      id: '/agendar'
      path: '/agendar'
      fullPath: '/agendar'
      preLoaderRoute: typeof AgendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendarRoute: AgendarRoute,
  LoginRoute: LoginRoute,
  SucessoRoute: SucessoRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
